apiVersion: v1
kind: Pod
metadata:
  name: devops-tools-pod
  labels:
    app: devops-tools
spec:
  volumes:
    - name: tools-storage
      emptyDir: {}
  initContainers:
    - name: install-tools
      image: ubuntu:20.04
      command:
        - sh
        - -c
        - |
          apt-get update && \
          apt-get install -y git vim curl && \
          apt-get clean
      volumeMounts:
        - name: tools-storage
          mountPath: /opt/tools
  containers:
    - name: devops-tools-container
      image: ubuntu:20.04
      command: [ "sleep", "infinity" ]
      volumeMounts:
        - name: tools-storage
          mountPath: /opt/tools
      env:
        - name: PATH
          value: "/opt/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  restartPolicy: Always
