apiVersion: v1
kind: Pod
metadata:
  name: devops-tools-pod
  labels:
    app: devops-tools
spec:
  volumes:
    - name: tools-storage
      emptyDir: {}
  initContainers:
    - name: install-tools
      image: ubuntu:20.04
      command:
        - sh
        - -c
        - |
          apt-get update && \
          apt-get install -y git vim curl zsh && \
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended && \
          cp -r /root/.oh-my-zsh /opt/tools/oh-my-zsh && \
          cp /root/.zshrc /opt/tools/.zshrc && \
          sed -i 's/\/root/\/opt\/tools/g' /opt/tools/.zshrc
      volumeMounts:
        - name: tools-storage
          mountPath: /opt/tools
  containers:
    - name: devops-tools-container
      image: ubuntu:20.04
      command: [ "sleep", "infinity" ]
      volumeMounts:
        - name: tools-storage
          mountPath: /opt/tools
      env:
        - name: PATH
          value: "/opt/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: ZSH
          value: "/opt/tools/oh-my-zsh"
        - name: ZSH_CUSTOM
          value: "/opt/tools/oh-my-zsh/custom"
        - name: SHELL
          value: "/bin/zsh"
        - name: HOME
          value: "/opt/tools"
      workingDir: /opt/tools
  restartPolicy: Always
